Add pre merge checks - fix jobs syntax in workflow
reboot-dev/pyprotoc-plugin pull request #21
Opened 2022-04-26 15:51 UTC by nizamutdinovb

2022-04-26 15:56 UTC, nizamutdinovb commented
@rjhuijsman I have made typo in not specifying `jobs` in the workflow.
This new PR is going to fix it.
Could you please approve this PR as well in order to merge it to main and made the workflow working?

2022-04-26 18:02 UTC, rjhuijsman commented
> @rjhuijsman Also I noticed that `PRIVATE_REPO_ACCESS_AS_REBOT_TOKEN` secret is not present in secrets. ![image](https://user-images.githubusercontent.com/54667918/165343266-6c2a2270-d045-4fa3-9809-509e359cd023.png)
> 
> Currently the secrets are configured to be used only with private repos. But `pyprotoc-plugin` is a public one. So now we have two options:
> 
> 1. to configure the secrets to be used by all repos
> 2. to change workflow to not use `PRIVATE_REPO_ACCESS_AS_REBOT_TOKEN` since there are no submodules in it
> 
> @rjhuijsman what do you think of it?

That's a great question! Let's go with option 2: unlike our other repos `pyprotoc-plugin` doesn't currently use submodules, so we should be able to clone the repository with the default `$GITHUB_TOKEN` (you can probably omit the entire `token` configuration entirely).

2022-04-26 18:02 UTC, rjhuijsman requested changes

2022-04-27 08:21 UTC, nizamutdinovb commented on .github/workflows/pre-merge-checks.yml
> +          submodules: recursive
Done. Now it's fine. Review re-requested.

2022-04-27 15:32 UTC, rjhuijsman commented
@nizamutdinovb the reason this pipeline is now failing is that we require Python version `>=3.9` for our tests to work. The default on GitHub action runners is 3.8.

How easy/hard would it be to make our GitHub Action Runner use Python 3.9?

2022-04-27 16:46 UTC, nizamutdinovb commented
> @nizamutdinovb the reason this pipeline is now failing is that we require Python version `>=3.9` for our tests to work. The default on GitHub action runners is 3.8.
> 
> How easy/hard would it be to make our GitHub Action Runner use Python 3.9?

@rjhuijsman I have installed python3.9 to the Runner during the Build before running the tests but it failed again:
https://github.com/reboot-dev/pyprotoc-plugin/runs/6197505246?check_suite_focus=true
and
https://github.com/reboot-dev/pyprotoc-plugin/runs/6197571899?check_suite_focus=true

2022-05-19 22:20 UTC, rjhuijsman commented
Replaced by https://github.com/reboot-dev/pyprotoc-plugin/pull/25

2022-05-19 22:20 UTC, closed without merging