Change 'rules_python' to be the same as in 'respect'
reboot-dev/pyprotoc-plugin pull request #37
Opened 2023-11-22 16:08 UTC by onelxj

2023-11-28 16:34 UTC, onelxj commented
@rjhuijsman any thoughts about the file structure we have for bazel?

2023-12-04 11:21 UTC, rjhuijsman commented on WORKSPACE.bazel
> +)
I think the key to good organization here is to treat this `pip_parse` as a repo-creating instruction. So we should organize it with the "repos", not the "deps".

I'd suggest creating a `python_repos.bzl` file and doing this work in there. Then in this `WORKSPACE.bazel` file calling `python_repos()` either just before or just after `repos()`.

2023-12-04 19:13 UTC, rjhuijsman requested changes
Cool, I like the new `requirements.in`->`requirements_lock.txt`! 👍🏻 

The tricky part in creating the order things are loaded is: when do you initialize the toolchain? There's not a great place for it in our traditional repos-deps organization.

The `rules_python` sort of dictates the answer: it has to happen after getting the `rules_python` repo, but before setting up the PyPI repos. And (see my inline comment about what "repos" and "deps" means) that means the toolchain should be in the middle of the "repos" steps.

So here's an order I think could work (not meant to compile, just to give the structure).

In the existing `repos.bzl`:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def repos():
    ...
	http_archive(
	    name = "rules_python",
	    sha256 = SHA,
	    strip_prefix = "rules_python-{}".format(VERSION),
	    url = "https://github.com/bazelbuild/rules_python/releases/download/{}/rules_python-{}.tar.gz".format(VERSION,VERSION),
	)
```

In a new `py_toolchains.bzl`:
```
load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

def toolchains():
  py_repositories()

  python_register_toolchains(
	    name = "python_3_10_...",
	    python_version = "3.10_...",
	)
```

And with `pypi_repos.bzl` as you already have it.

Then the order can be:
1. `repos.bzl`
2. `py_toolchains.bzl`
3. `pypi_repos.bzl`
4. `deps.bzl` (very small now that all Python stuff has moved elsewhere)

2023-12-05 10:59 UTC, rjhuijsman approved these changes
Great, thank you! Just a few naming suggestions - then let's ship it! 👍🏻

2023-12-05 10:59 UTC, rjhuijsman commented on bazel/py_toolchains.bzl
> +def toolchains(repo_mapping = {}):
Let's make it extra obvious and call this `py_toolchains`. Then also call it that in the `WORKSPACE.bazel`.

2023-12-05 10:59 UTC, rjhuijsman commented on WORKSPACE.bazel
> +load("//bazel:pypi_repos.bzl", pyprotoc_plugin_pypi_repos = "pypi_repos")
Everything in this repo is about `pyprotoc_plugin`, so it's not super useful to add that prefix to the name. I'd keep it at just `pypi_repos`.

2023-12-05 10:59 UTC, rjhuijsman commented on bazel/deps.bzl
> +    install_deps(repo_mapping = repo_mapping)
Here the name `install_deps` makes it a little harder to notice that this is the PyPI deps, so I'd consider importing `install_deps` as `pypi_deps`.

2023-12-05 10:59 UTC, rjhuijsman commented on bazel/pypi_repos.bzl
> +generated by `bazel run :requirements.update` command."""
Some wording suggestions:

```suggestion
"""Defines local PyPI-based repositories. Their deps
should be installed later in WORKSPACE file to be accessible.
`pip_parse` takes a `requirements_lock` file as input, which is
generated by the `bazel run :requirements.update` command."""
```

2023-12-06 14:24 UTC, merged